"""Cross-layer data contracts and service Protocols — the dependency-inversion seam.

Everything references this layer; it references nothing domain-specific (only ``shared``).
See ADR-0001 for why the contracts live here rather than beside their subsystems.
"""

from billet.contracts.config import GlobalConfig
from billet.contracts.doctor import (
    BERTH_COPIED_FILES,
    BERTH_HASHED_FILES,
    BERTH_UNCHECKED_SNIPPETS,
    BERTH_VERSION_FILE,
    ENTRYPOINT_LOG_PREFIX,
    BerthFileState,
    BerthFileStatus,
    BerthStatus,
    DoctorAccess,
    DoctorFilters,
    DoctorReport,
    DoctorSkip,
    PackagedBerth,
    RunningBerthState,
    RuntimeReport,
    RuntimeState,
    StampState,
    StampStatus,
    WorkspaceBerthRead,
    WorkspaceProbe,
    WorkspaceRuntimeRead,
)
from billet.contracts.host import (
    HostPowerState,
    HostProvider,
    HostSpec,
    HostStatus,
    ProvisioningSpec,
)
from billet.contracts.metrics import (
    ContainerMetrics,
    CpuMetrics,
    DiskMetrics,
    HostMetrics,
    MemoryMetrics,
    MetricsAccess,
)
from billet.contracts.plan import NullPlanObserver, Plan, PlanObserver, PlanStep, StepKind
from billet.contracts.workspace import (
    ContainerAccess,
    DevcontainerFacts,
    RemoteHost,
    SourceAccess,
    SshConfigAccess,
    SshConfigBlock,
    WorkspacePlan,
    WorkspacePlanStep,
    WorkspaceSpec,
    WorkspaceStatus,
    WorkspaceStepKind,
)

__all__ = [
    "BERTH_COPIED_FILES",
    "BERTH_HASHED_FILES",
    "BERTH_UNCHECKED_SNIPPETS",
    "BERTH_VERSION_FILE",
    "ENTRYPOINT_LOG_PREFIX",
    "BerthFileState",
    "BerthFileStatus",
    "BerthStatus",
    "ContainerAccess",
    "ContainerMetrics",
    "CpuMetrics",
    "DevcontainerFacts",
    "DiskMetrics",
    "DoctorAccess",
    "DoctorFilters",
    "DoctorReport",
    "DoctorSkip",
    "GlobalConfig",
    "HostMetrics",
    "HostPowerState",
    "HostProvider",
    "HostSpec",
    "HostStatus",
    "MemoryMetrics",
    "MetricsAccess",
    "NullPlanObserver",
    "PackagedBerth",
    "Plan",
    "PlanObserver",
    "PlanStep",
    "ProvisioningSpec",
    "RemoteHost",
    "RunningBerthState",
    "RuntimeReport",
    "RuntimeState",
    "SourceAccess",
    "SshConfigAccess",
    "SshConfigBlock",
    "StampState",
    "StampStatus",
    "StepKind",
    "WorkspaceBerthRead",
    "WorkspacePlan",
    "WorkspacePlanStep",
    "WorkspaceProbe",
    "WorkspaceRuntimeRead",
    "WorkspaceSpec",
    "WorkspaceStatus",
    "WorkspaceStepKind",
]
